### ISSUE TITLE
Create react boilerplate for front end

### ISSUE THREAD

**Issue by mmcadoulos** [ALLHUBS-Jan-2024-Liftoff/Black-Jackets#2]
Run `npm create vite@latest`
Project name: findAGig-UI
Framework: React
Variant: JavaScript

**Comment by fowlerrc** [comment]
Pretty sure I've gotten everything set up for both front end and back end the way Phillip showed is in the lecture. But if you guys could go ahead and look at what I've done and see if anything is wrong or missing, that would be great. But when I cloned our project into IntelliJ it looks to be all there. I don't want to close these tasks until we're sure that I've done everything right though.

**Comment by mmcadoulos** [comment]
EDIT: I was wrong about this last comment. That is just something that needs to be run locally for each person who clones it. You can go ahead and mark this as done!


All that is left is to run `npm install` inside the BlackJackets-ui folder and push that up
