### ISSUE TITLE
add .gitignore from lecture-ressources

### ISSUE THREAD

**Issue by mmcadoulos** [ALLHUBS-Jan-2024-Liftoff/Black-Jackets#3]
add file named `.gitignore` to project folder
fill file with the text that Phillip shared in lecture-resources

**Comment by fowlerrc** [comment]
Pretty sure I just completed this, but can anybody check me to make sure I did it right? If you click on the CODE on the upper left in Git Hub, you should find my "git ignore" addition listed right there.

**Comment by mmcadoulos** [comment]
the file should be renamed to ".gitignore" and I think it will be good to go!
